server:
  port: 8083
       
spring:
  messages:
    basename: messages/error/errorMessages
    cache-duration: -1
    encoding: UTF-8
  
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: admin
    
  jackson:
    date-format: MM/dd/yyyy
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  http:
    encoding:
      charset: UTF-8
      enabled: true  application:    name: orderItem

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
